[package]
name = "drivedb-bench"
version = "0.11.0"
authors = ["vthriller <unixway.drive+rs@gmail.com>"]

[dependencies]
drivedb = { path = ".." }
clap = ">=0.6.6"
regex = "0.2"
regex-cache = "0.1.6"
